sudo: false

language: php

php:
  - 7.2

branches:
  only:
    - master
    - "/^\\d+\\.\\d+\\.\\d+-?\\d+?$/"

script:
  - echo "NO PHPUNIT tests"

deploy:
  provider: releases
  api_key:
    secure: d7444de9c963582d1a92a9891aafdf38034c2234
    file: "build.tar.gz"
    skip_cleanup: true
    draft: true