sudo: false
language: php
php:
- 7.2
env:
  global:
  - secure: pVamQ9PECyXT6P/capJZYkjQ9rhU6WJqPiyLXTxyBK30KqjW+H71TnSsC/Fq3IgVYRccNEOJCTzPCDQwOfXKkoUUZCrsNt9lUbb7F2xJfK603G8bYaS5UulgFNI333Vayeh8/ySe3S1rf0q3ZQkMtyPz1rZumdMlK3CBOWdR75a7mZVMXa1qXKFyoV51LyEW62r25+jnJmvpptpbMK6HKtZsDUGNlc/fxnoRdQdpjQN/c47FeLM9GysBMGbz7tyrQzi/FoM4mC3wwybcJN8JIZ5S1bOFYVO0YIg/AF2305Ianjx3KFwFWnsFsieHn/n5cUmaJndHcHpum4TJoP8++lRX5uUNZkuHlRvmng5joKTVxUGltzpInS9xVxqVkDVooXJvgtrskocZm5jgzKT7gfgnX8ZUx4wIrEjw1hqqRRSulhOuLfg+u+4LPcyJFEP4oDfnrMAvg62q4YuJjqMT5+Q5S1WA+7Vj+UD9iRjpLG8kRYmNzWhUE2I1BiJTAb4rZ/M8kI2jIvrQKcwJ2EAp5yZYWszEmy4KrK+/mtgrpG+hauPtvHbNBFsogN7YxDPVYq3yS0Ry62cymFhCjMrglZLlkt0bSd7TYaq65T5jp6108BexG8yxeuAqH5xUQKT8+Qb7wYsmZmotTobC2OFrVJjzLaLS6sf9LiGXyYfPZ7c=
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+-?\\d+?$/"
script:
- echo "NO PHPUNIT tests"
before_deploy:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- export REPO=stadeleon/$(echo $TRAVIS_REPO_SLUG |cut -d "/" -f2)
- docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .
- docker push $REPO
- tar -czf build.tar.gz *
- rm -rf `ls | grep -v build.tar.gz`
deploy:
  provider: releases
  api_key:
    secure: I7ztoqcJOPfQ+PLAq9BhUb3nauSmyBMOUWVIREkBkMeKvgFYcjkgQCz35/z/ab41Qi4TptiU6ZiIfG6YiRV1QPS9NIcoYKYNInqLJ0ePACCzjr7nkqIujp0ZQDXi4ohI3GRUg4KZkKdWL2ujjxZh7mN2r8ROadC1ewaTcVpmdPiAh/HdnfeKZjjwwZ+PDcc1TrumeSlnHr4ce2unib1CFrkFOL+vdjA/Q4xOWA1uvQJPhr0j/fsPsEcWarTCe2FoeAnYwhqn1r7zqC71FGDIKKLpj1CNP6jmeKwFG4dhH9UBzS7CDjakFkfbeH0Ba+AnY3CoU27ymNvjnv9QLgPPK5T0Jc+4SeyfL0mwNWijxPxwsdTALGA3wpZZCwJtxGV/oFzSVQNUXgFrN6uQLKMNIIlbTLvsfMl8WXUsP6lPfmLfBBb6KR9FyxDTomLFiNvbZalN6XsvCXUAA4fSCKv4I0OTHAZTPjPpW8xaK78Dj/dntUxd1lBJmM8GGAe91oZXsBpQ3BkYvqquLBUBfDBneEsznmxdz4p2qyo7yXPx6VYZvr2FWcVmL7K2p1iRJJ/NLnAVhp0DR5oEkIoau/UzlTE1pIkqdFPqjqfspcNE6Wll9poc9UEqMoG4PbzLB2NgSryu8MEPANR+xm+/sLF+vI5fBII1J2drSbN3feZENKM=
  file: build.tar.gz
  skip_cleanup: true
  on:
    repo: stadeleon/wp-test-image
    tags: true
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
