sudo: false
language: php
php:
  - 7.2
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+-?\\d+?$/"
script:
  - echo "NO PHPUNIT tests"
deploy:
  provider: releases
  api_key:
    secure: FrIkSNCIG48q0nfc9WeVDaaPO2k8Ac4dKHH/WRumony6y3g1A478qZt4gTBg61e48xXsl8sqk9UvNp1TnzCGTz5XBJY9yM36jpBhySZJvCFI8x7RhNCWusiQOzY6IC3BP7GiY7aDNsLEXLbfGEQLEdBfMrEXghq1LFfuQnSS6gAJ4DsaeD8crPCL3vb2aAOrov3zDWdwA/2gBXRmq4ftfxIxSbinV3BMQ9Iiyd3tDSK7gz2rkivjnxaRE84vx3iAfpkb0cPckr8o3+/rg4FvzWt2Vgh7e+MRCIXCpK9c4Suyam8GFnsgP7aeT0w44L/fhUhRzEgmkbQBKXq9GX5m8275trRtPpoVUzNdWN/kZghgKWCEVaSSVtucVxh7gsBJW5luJQVnwUw9jgWZKXat5VKUwPfpLfha4//FF+j1+DKX3lgB5vB2clE1nl+kgVvCFwdKp0YlKxKGtq53O/SfUdyjWg728JxizYrlaaey2U0ozpP4t2Ks+6T4wTXOtRm7LbcumsHQGIgFCKwBQHPLZWM4cMm5uGDrhOtlHncEKShrCxRxUOAexFJmFR4ELaNZPQhF58HgmMruWP9YXYcCkozwHa8A5ZrQytuHKjduFzkJ4qujwezX6EAyUkkc575gX8qTujMqcFl9GKK0ZnGVwI5DiorG1TleQQDU6BbfgG0=
    file: build.tar.gz
    skip_cleanup: true
    draft: true
env:
  global:
  - secure: FrIkSNCIG48q0nfc9WeVDaaPO2k8Ac4dKHH/WRumony6y3g1A478qZt4gTBg61e48xXsl8sqk9UvNp1TnzCGTz5XBJY9yM36jpBhySZJvCFI8x7RhNCWusiQOzY6IC3BP7GiY7aDNsLEXLbfGEQLEdBfMrEXghq1LFfuQnSS6gAJ4DsaeD8crPCL3vb2aAOrov3zDWdwA/2gBXRmq4ftfxIxSbinV3BMQ9Iiyd3tDSK7gz2rkivjnxaRE84vx3iAfpkb0cPckr8o3+/rg4FvzWt2Vgh7e+MRCIXCpK9c4Suyam8GFnsgP7aeT0w44L/fhUhRzEgmkbQBKXq9GX5m8275trRtPpoVUzNdWN/kZghgKWCEVaSSVtucVxh7gsBJW5luJQVnwUw9jgWZKXat5VKUwPfpLfha4//FF+j1+DKX3lgB5vB2clE1nl+kgVvCFwdKp0YlKxKGtq53O/SfUdyjWg728JxizYrlaaey2U0ozpP4t2Ks+6T4wTXOtRm7LbcumsHQGIgFCKwBQHPLZWM4cMm5uGDrhOtlHncEKShrCxRxUOAexFJmFR4ELaNZPQhF58HgmMruWP9YXYcCkozwHa8A5ZrQytuHKjduFzkJ4qujwezX6EAyUkkc575gX8qTujMqcFl9GKK0ZnGVwI5DiorG1TleQQDU6BbfgG0=

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
