version: '3.3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    volumes:
      - sessions:/sessions
    restart: always
    environment:
#        - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=mysql

  mysql:
     image: mysql:5.7
     ports:
       - "3306:3306"
       depends_on:
         - phpmyadmin
       volumes:
         - /var/lib/mysql:/var/lib/mysql
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: wp_test
         MYSQL_USER: wpuser
         MYSQL_PASSWORD: wppassword

  wp:
     build: .
#     image: stadeleon/wp-test-image:0.0.1-6
     depends_on:
       - mysql
     ports:
#       - 80:80
#       - 443:443
#     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: root
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: root
volumes:
  sessions: {}
  mysql:
    driver: "local"
  phpmyadmin:
    driver: "local"
