version: '3'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: wp-test-db
#       MYSQL_USER: wp-user
#       MYSQL_PASSWORD: wp-pass

   wp:
#     build: .
     image: stadeleon/wp-test-image
     depends_on:
       - mysql
     ports:
       - 80:80
#     ports:
#       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: root
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: root
volumes:
    db_data:
